[package]
name = "miden-package-introspection"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "miden_package_introspection"
path = "src/main.rs"

[dependencies]
miden-mast-package = "0.19.1"
serde_json = "1.0.145"
winter-utils = "0.13.1"
